# Generated by Django 5.0.6 on 2024-06-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0007_remove_fuelstation_control_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
